print('Фамилия: ')
surname = input()
print('Имя: ')
name = input()
print('Отчество: ')
secondname = input()
print('Дата рождения: ')
birthday = input()
print('Адрес: ')
address = input()
print('Банковские реквизиты: ')
bank = int(input())
print('Телефон: ')
phonenumber = input()
print('Паспортные данные: ')
passport = input()

